[package]
name = "static-site"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
axum = "0.8.4"
notify = "8.0.0"
tokio = {version = "1.44.2", features = ["full"]}
tower = "0.5.2"
tower-http = {version = "0.6.2", features = ["fs"]}
tower-livereload = "0.9.6"
